  services:

    app:
      build: ./
      networks:
        - app-network
      volumes:
        - ./:/var/www/html
      command: bash -c "composer install && php -S 0.0.0.0:80 -t public"
      ports:
      - 80:80
      restart: unless-stopped

  networks:
    app-network:
      driver: bridge

  volumes:
    db-data:
      driver: local